scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: 30s
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: 'ahoy-dtu'
    honor_labels: true
    scrape_interval: 30s
    static_configs:
      - targets: ['ahoy-dtu.fritz.box']
